






CREATE VIEW [dbo].[vwGetAllApplyNowData]
AS
/*************************************************
  Author:      Daniel Kelleher
  Create Date: 4/21/2020
  Description: Gets all Apply Now Data.
*************************************************/

	SELECT tapp.[ApplicationID] as [Application ID]
		 , ta.[ApplyNowID] as [ApplyNow ID]
		 , tblP.[PersonID] AS [PersonID]
		 , tapp.[AppValidation]
		 , tapp.[CanvasPolicyNumber]
		 , tblP.[FirstName]
		 , tblP.[MiddleName]
		 , tblP.[LastName]
		 , tblPT.[Type] AS [PersonType]
		 , tblPT.[Descr] AS [PersonDescr]
		 , tblRT.[Descr] AS [RelationshipDescr]
		 , tblP.[DOB]
		 , tblPE.[EmailAddress]
		 , tsapp.[StateShort] AS [ApplicationStateShort]
		 , tsapp.[StateLong] AS [ApplicationStateLong]	
		 , tblGT.[Type] AS [GenderType]
		 , tblGT.[Descr] AS [GenderDescr]
		 , tpr.[Type] AS [PeriodType]
		 , tpr.[Descr] AS [PeriodDescr]
		 , tpd.[Type] AS [ProductType]
		 , tpd.[Descr] AS [ProductDescr]
		 , pt.[Type] AS [PlanType]
		 , pt.[Descr] AS [PlanTypeDescr]
		 , tasts.[Type] AS [StatusType]
		 , tapp.[Premium]
		 , tapp.[ForCompany]
		 , ta.[Percentage]
		 , tblPP.[PhoneNumber]
		 , tblPHT.[Type] AS [PhoneType]
		 , tblPHT.[Descr] AS [PhoneDescr]
		 , tblDSDE.[Signature]
		 , tblEMT.[Type] AS [EmailType]
		 , tblEMT.[Descr] AS [EmailDescr]		
		 , tblST.[Type] AS [SSNTINType]
		 , tasts.[Descr] AS [StatusDescr]
		 , tblST.[Descr] AS [SSNTINDescr]
		 , tblP.[SSNTIN]
		 , tblA.[AddressTypeID]
		 , tblA.[Address1]
		 , tblA.[Address2]
		 , tblA.[City]
		 , tblA.[ZipCode]
		 , SOF.[SourceOfFundsID]
		 , SOF.[Contribution]
		 , SOF.[ContributionYear]
		 , SOF.[Transfer]
		 , SOF.[Rollover]
		 , SOF.[Conversion]
		 , SOF.[ConversionYear]
		 , tapp.[StateID] AS [ApplicationStateID]
		 , tblA.[StateID] AS [AddressStateID]
		 , tblSA.[StateShort] AS [AddressStateShort]
		 , tblSA.[StateLong] AS [AddressStateLong]				 
		 , tblEP.[ChangePolicies]
		 , tblEP.[PolicyNumber]
		 , tblEP.[IssueDate]		 
		 , tblP.[ResidentAlien]
		 , tblP.[USCitizen]
		 , tblP.[GenderTypeID]	
		 , tblPE.[EmailTypeID]
		 , tppp.[PeriodTypeID]		 
		 , tppp.[ProductTypeID]		 
		 , tppp.[PlanTypeID]		
		 , tapp.[StatusTypeID]
		 , tblPP.[PhoneTypeID]
		 , tblPSDE.[Charged]
		 , tblPSDE.[PaymentAmount]		 
		 , ta.[RelationshipTypeID]		 
		 , ta.[PersonTypeID]		 
		 , tblP.[BirthStateID]
		 , tblSP.[StateShort] as BirthState
		 , tblSP.[StateLong] as BirthStateName
		 , tblP.[IDNumber]		 
		 , tblU.[UserId]
		 , tblU.[PersonID] AS [UserPersonID]
		 , tblU.[UserTypeID]
		 , tblUU.[Type] AS [UserType]
		 , tblUU.[Descr] AS [UserDescr]
		 , tblU.[Email]
		 , tblU.[Pass]
		 , tblU.[Attempt]
		 , tblU.[locked]
		 , tblU.[Last_Login]
		 , tblU.[IsAdmin]
		 , tblU.[PasswordChangeDate]
		 , tblU.[Question1]
		 , tblU.[Answer1]
		 , tblU.[Question2]
		 , tblU.[Answer2]
		 , tblU.[Question3]
		 , tblU.[Answer3]
		 , tblU.[Question1ChangeDate]
		 , tblU.[Answer1ChangeDate]
		 , tblU.[Question2ChangeDate]
		 , tblU.[Answer2ChangeDate]
		 , tblU.[Question3ChangeDate]
		 , tblU.[Answer3ChangeDate]	
		 --, tblLNDE.[ConversationID] as [LexisNexisConversationID]
	  FROM [dbo].[tblApplication] tapp with(nolock) 
	  left join [dbo].[tblApplyNow] ta with(nolock) on tapp.[ApplicationID] = ta.[ApplicationID]
	  left join [dbo].[tblProductPlanPeriod] tppp with(nolock) on tppp.[ProductPlanPeriodID] = tapp.[ProductPlanPeriodID]
	  left join [dbo].[tblState] tsapp with(nolock) on tsapp.[StateID] = tapp.[StateID]
	  left join [dbo].[tblPeriodType] tpr with(nolock) on tpr.[PeriodTypeID] = tppp.[PeriodTypeID]
	  left join [dbo].[tblProductType] tpd with(nolock) on tpd.[ProductTypeID] = tppp.[ProductTypeID]
	  left join [dbo].[tblStatusType] tasts with(nolock) on tapp.[StatusTypeID] = tasts.[StatusTypeID]
	  left join [dbo].[tblPlanType] pt with(nolock) on pt.[PlanTypeID] = tppp.[PlanTypeID]
	  left join [dbo].[tblPerson] tblP with(nolock) on tblP.[PersonID] = ta.[PersonID]
	  left join [dbo].[tblPersonType] tblPT with(nolock) on ta.[PersonTypeID] = tblPT.[PersonTypeID]
	  left join [dbo].[tblRelationshipType] tblRT with(nolock) on ta.[RelationshipTypeID] = tblRT.[RelationshipTypeID]
	  left join [dbo].[tblGenderType] tblGT with(nolock) on tblP.[GenderTypeID] = tblGT.[GenderTypeID]
	  left join [dbo].[tblSSNTINType] tblST with(nolock) on tblP.[SSNTINTypeID] = tblST.[SSNTINTypeID]
	  left join [dbo].[tblState] tblSP with(nolock) on tblSP.[StateID] = tblP.[BirthStateID]
	  left join [dbo].[tblAddress] tblA with(nolock) on tblA.[PersonID] = tblP.[PersonID]
	  left join [dbo].[tblState] tblSA with(nolock) on tblSA.[StateID] = tblA.[StateID]
	  left join [dbo].[tblPersonPhone] tblPP with(nolock) on tblPP.[PersonID] = tblP.[PersonID]  
	  left join [dbo].[tblPhoneType] tblPHT with(nolock) on tblPHT.[PhoneTypeID] = tblPP.[PhoneTypeID]
	  left join [dbo].[tblPersonEmail] tblPE with(nolock) on tblPE.[PersonID] = tblP.[PersonID]  
	  left join [dbo].[tblEmailType] tblEMT with(nolock) on tblEMT.[EmailTypeID] = tblPE.[EmailTypeID]  
	  left join [dbo].[tblSourceOfFunds] SOF with(nolock) on SOF.[ApplicationID] = tapp.[ApplicationID]  
	  left join [dbo].[tblUser] tblU with(nolock) on tblU.[PersonID] = tblP.[PersonID]
	  left join [dbo].[tblUserType] tblUU with(nolock) on tblUU.[UserTypeID] = tblU.[UserTypeID]
	  left join [dbo].[tblDocuSignDataElements] tblDSDE with(nolock) on tblDSDE.[ApplyNowID] = ta.[ApplyNowID]
	  left join [dbo].[tblExistingPolicy] tblEP with(nolock) on tblEP.[ApplyNowID] = ta.[ApplyNowID]
	  --left join [dbo].[tblLexisNexisDataElements] tblLNDE with(nolock) on tblLNDE.[ApplyNowID] = ta.[ApplyNowID]
	  left outer join [dbo].[tblPlaidStripeDataElements] tblPSDE with(nolock) on tblPSDE.[ApplyNowID] = ta.[ApplyNowID]
	  ----where ta.[ApplyNowID] = 1
	  ----where ta.PersonID = 1
	  where tapp.AppValidation = 0 and ta.ApplyNowID is not null
	  --order by tapp.[ApplicationID] asc,ta.ApplyNowID asc, ta.[PersonID] asc