CREATE TYPE [DataSync].[tblTransposeApplyNowApplication_dss_BulkType_124b7692-e026-485b-a37b-686f68327b41] AS TABLE (
    [TransposeApplyNowApplicationID] INT      NOT NULL,
    [ApplicationID]                  INT      NULL,
    [ApplyNowIDOwner]                INT      NULL,
    [ApplyNowIDJointOwner]           INT      NULL,
    [ApplyNowIDAnnuitant]            INT      NULL,
    [ApplyNowIDJointAnnuitant]       INT      NULL,
    [ApplyNowIDBeneficiary1]         INT      NULL,
    [ApplyNowIDBeneficiary2]         INT      NULL,
    [ApplyNowIDBeneficiary3]         INT      NULL,
    [ApplyNowIDBeneficiary4]         INT      NULL,
    [ApplyNowIDBeneficiary5]         INT      NULL,
    [ApplyNowIDReplacementCompany]   INT      NULL,
    [ApplyNowIDUnknown]              INT      NULL,
    [ApplyNowIDAgent]                INT      NULL,
    [CreatedDate]                    DATETIME NULL,
    [LastModifiedDate]               DATETIME NULL,
    [sync_update_peer_timestamp]     BIGINT   NULL,
    [sync_update_peer_key]           INT      NULL,
    [sync_create_peer_timestamp]     BIGINT   NULL,
    [sync_create_peer_key]           INT      NULL,
    PRIMARY KEY CLUSTERED ([TransposeApplyNowApplicationID] ASC));

